version: "3.3"
services:
  db:
    image: 'postgres:12.4-alpine'
    environment:
      POSTGRES_USER: athenahero
      POSTGRES_PASSWORD: athenahero
      POSTGRES_DB: athenahero
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
  athenahero:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - 5000:5000
    environment:
      FLASK_APP: athenahero
      ATHENAHERO_SQLALCHEMY_DATABASE_URI: "postgresql://athenahero:athenahero@db:5432/athenahero"
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
    volumes: 
      - "./athenahero:/app/athenahero"
      - "./Makefile:/app/Makefile"
      - "./tests:/app/tests"
    depends_on: ["db"]
    command: 
        make start
