"""add workgroup and index to submission date

Revision ID: 68667e0da916
Revises: f28196725926
Create Date: 2020-08-17 18:55:43.328652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68667e0da916'
down_revision = 'f28196725926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_executions', sa.Column('workgroup', sa.Text(), nullable=True))
    op.create_index(op.f('ix_query_executions_submission_datetime'), 'query_executions', ['submission_datetime'], unique=False)
    op.create_unique_constraint(None, 'query_executions', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_executions', type_='unique')
    op.drop_index(op.f('ix_query_executions_submission_datetime'), table_name='query_executions')
    op.drop_column('query_executions', 'workgroup')
    # ### end Alembic commands ###
