"""create query_executions table

Revision ID: 9665fcbf9b01
Revises: 
Create Date: 2020-08-24 20:49:22.492733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9665fcbf9b01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_executions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('statement_type', sa.String(length=10), nullable=False),
    sa.Column('output_location', sa.Text(), nullable=False),
    sa.Column('encryption_option', sa.String(length=10), nullable=True),
    sa.Column('kms_key', sa.Text(), nullable=True),
    sa.Column('context_database', sa.Text(), nullable=True),
    sa.Column('context_catalog', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_state_change_reason', sa.Text(), nullable=True),
    sa.Column('submission_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('completion_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('engine_execution_time_in_millis', sa.Integer(), nullable=True),
    sa.Column('total_execution_time_in_millis', sa.Integer(), nullable=False),
    sa.Column('query_queue_time_in_millis', sa.Integer(), nullable=True),
    sa.Column('query_planning_time_in_millis', sa.Integer(), nullable=True),
    sa.Column('service_processing_time_in_millis', sa.Integer(), nullable=True),
    sa.Column('data_manifest_location', sa.Text(), nullable=True),
    sa.Column('data_scanned_in_bytes', sa.BigInteger(), nullable=False),
    sa.Column('workgroup', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_query_executions_submission_datetime'), 'query_executions', ['submission_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_executions_submission_datetime'), table_name='query_executions')
    op.drop_table('query_executions')
    # ### end Alembic commands ###
