import os

SQLALCHEMY_DATABASE_URI = os.environ.get("ATHENAHERO_SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = False

ATHENAHERO_USERNAME = os.environ.get("ATHENAHERO_USERNAME")
ATHENAHERO_PASSWORD = os.environ.get("ATHENAHERO_PASSWORD")
